//
// Created by reza on 05/03/23.
//

#ifndef TOWERS_OF_HANOI_SOLVER_CONSTANTS_H
#define TOWERS_OF_HANOI_SOLVER_CONSTANTS_H

#include <cmath>

const int TOWER_SIZE = 16;
const int NUMBER_OF_PEGS = 5;
const int ABSTRACT_SIZE = 12;
const int REMAINED_SIZE = TOWER_SIZE - ABSTRACT_SIZE;
const int NUMBER_OF_THREADS = 12;
const int NUMBER_OF_SPLITS = 8 * NUMBER_OF_THREADS + 2;

#endif //TOWERS_OF_HANOI_SOLVER_CONSTANTS_H
